### ISSUE TITLE
Link ordering/Permalinks

### ISSUE THREAD

**Issue by jhollist** [ropensci-archive/reproducibility-guide#12]
Currently the site is building the links with the blog style permalinks and is also ordering those in a manner that I can't seem to figure out.  

Any thoughts on how to change the ordering (i.e [here (http://ropensci.github.io/reproducibility-guide/)) of the links?  Should we override the permalinks with shorter, less bloggy links?  I don't have a lot of experience with Jekyll, but I think we can specifiy the specific link with the YAML on each page.

**Comment by iamciera** [comment]
Yes.  I agree.   I think we should actually have a side navigation bar for these instead. I can do this once we get a better idea of the structure.  I was going to wait till most of the content was decided.  BTW, the links are ordered by date, so feel free to change the date on the files to change the order.

**Comment by jhollist** [comment]
Order I am getting is not associated withe the date. 

Current order is:
- Further reading
- Best Practices for Project Meta Data
- Useful Workflows
- Introduction to Tools
- Data Archiving

I did try changing the dates and didn't work for me...

I like the idea of re-doing the nav.  Won't worry about this more and will close the issue.
