### ISSUE TITLE
Site Organization

### ISSUE THREAD

**Issue by jhollist** [ropensci-archive/reproducibility-guide#14]
First Cut at an outline for orgnaizing/navigating the site.  I am not wed to any of this.  I just like lists!
- Introduction
  - Definitiion (Gradient of and Focus for the Guide)
  - Tools
- Workflows
  - @EDiLD 
  - Kieran 
  - Web
  - RStudio (0.98.745)
- Expanding Reproducibility (see [#5](https://github.com/ropensci/reproducibility-guide/issues/5#issuecomment-39124710))
- Related Topics
  - Data Archiving
  - Metadata Best Practices
  - Dependencies
- Further Reading

**Comment by iamciera** [comment]
Looks good!  I want to include data archiving somewhere, but I honestly need to do a bit more research on the topic to see what else to include.  I will deal with the site layout when we have an agreement on structure.  And like I mentioned before, in the issue about making it look less bloggy, I will put them all as side navigation that will be present on every page.  The center area will be where the content is.  I will start working on that this afternoon. 

I also want to style the site a little more, keeping it subtle, but changing the colors a bit to match the rOpenSci blue theme they have going.

**Comment by jhollist** [comment]
My first cut, I forgot to include the Data Archiving and Metadata.  I edited it above to include that.

**Comment by iamciera** [comment]
I was just talking with @karthik and we think it would be best to change each of these into their own pages.  I think I will start working on site structure right away.  I will leave the post section for now for you all to keep adding content the same way, but when I finish I will move it all to the content to their proper sections.

**Comment by jhollist** [comment]
Just cleaning up some of the issues.  I think we have mostly addressed this and/or have other open issues that more closely match the current organization of the page.
