### ISSUE TITLE
Collaborators Section

### ISSUE THREAD

**Issue by iamciera** [ropensci-archive/reproducibility-guide#44]
What do you guys think about the collaborators section by the made possible by header on main page?  I always enjoy learning about the people behind projects, even if it is just a some names and hyperlinks.  If we encourage people to add their name when they contribute, it would likely promote collaboration.  But then again, seems a little self promoting?  

What do you guys think?

**Comment by karthik** [comment]
:+1:

**Comment by jhollist** [comment]
I agree with Karthik.  It is a good thing.  And a little self-promotion is
not necessarily a bad thing!

So, I say we keep it and encourage everyone to add their names!

On Tue, Apr 15, 2014 at 4:07 PM, Karthik Ram notifications@github.comwrote:

> [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ropensci/reproducibility-guide/issues/44#issuecomment-40527717
> .

## 

Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087
