### ISSUE TITLE
References Highlight

### ISSUE THREAD

**Issue by iamciera** [ropensci-archive/reproducibility-guide#47]
I like the idea that this site is a curation of information where one function is the uniting  of existing material.  If you guys have excellent references pertaining to a particular section, even if they are in the References section, we should highlight them in the sections.  Maybe in a resources section on each page. We should keep them to only the best though, so not to overwhelm.  Feel free to add as you please.

**Comment by benmarwick** [comment]
Agreed, we can't cover everything, especially when many topics are covered so well elsewhere. A curated/annotated set of resources is a good niche we can fill with this site.
