### ISSUE TITLE
About text: suggested edits

### ISSUE THREAD

**Issue by eacheson** [ropensci-archive/reproducibility-guide#84]
As the first thing anyone reads, the "About" text on the index page should consist of well-edited paragraphs.

Some issues:
1. "Unfortunately, reproducibility of results is actually becoming increasingly more difficult, owing to the variety of ways of approaching analysis and incapability of data structures and file types." Is it really becoming MORE difficult? I doubt that. Edit this sentence to avoid making a potential untrue statement, or provide references. Then, "incapability of data structures", is this supposed to say "incompatibility"? Otherwise I'm not sure I understand how file types and data structures can be incapable.
2. "While technology increasingly evolves": "increasingly" or "increase" appears in 3/4 of the previous sentences, delete or replace with something more meaningful
3. "creating entirely new section": creating _an_ entirely new section
4. "Contribution to the guide is highly encouraged by collaboration through Github.": add link to the github site, ideally to a page with instructions on how to contribute

**Comment by benmarwick** [comment]
Thanks for your suggestions! I've made a pull request that will update the text according to your observations.

In fact there is a guide to contributing here: http://ropensci.github.io/reproducibility-guide/sections/collaborationGuide/ Please feel free to follow those instructions if you have more suggestions for improvement (it will be quicker than waiting for me or one of the other original contributors to do it!).
