### ISSUE TITLE
Reproducibility Guide Future?

### ISSUE THREAD

**Issue by iamciera** [ropensci-archive/reproducibility-guide#86]
This guide is getting pretty rusty.  We should really think about what the function of it is. It has a lot of useful information, but I feel like the information is hard absorb.  There are too many sections, uneven content, and outdated information.  

The first question is, in the condition the site is in now, does it serve a valuable function? And/Or does it do any harm staying up in the condition it is in?

If we decide to keep it going, we should figure out how to make the site better.  What do we need to change? What can stay? Organization? Ect?

One idea: Reproducibility is such a malleable topic and there are no real hard rules, making the creation of a good guide extremely difficult.  I really like the [questions section](http://ropensci.github.io/reproducibility-guide/sections/checklist/). Maybe we could put that on the front page and link content/references to learn more along those specific questions. Reproducibility is such a dry topic, I like the idea the front page having useful information that can be quickly digestible.  Then give the audience the ability to look deeper with a few highlighted references.

Also, I really like the introduction.

Any thoughts?

**Comment by szeitlin** [comment]
Some sections are more complete that others. The ones on Workflow and Data Archiving, for example, seem like stubs. 

I like that there are separate sections, but it might be good to have summaries of what's in them? This kind of thing can be very subjective, though. Might be good to get some analytics on there and see what people are actually using/not using.

**Comment by kinow** [comment]
Would be nice if there were cases of reproducibility being applied to real world projects. Say a lab in some university followed what is described in one of the sections, they could share they story with us.

The stories could have a description of what went well - and why - and what went not so well. That could generate feedback for the current reproducibility guide, and also motivate and help other users trying to implement it for the first time in their projects.

Just my 0.02 cents :-)

**Comment by jjchern** [comment]
Why not turn it into a book using `bookdown`?
