### ISSUE TITLE
Fix page build problems

### ISSUE THREAD

**Issue by iamciera** [ropensci-archive/reproducibility-guide#89]
After Github switched to a different Jekyll we get page build problems:

> You are currently using the 'redcarpet' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

This needs to be fixed.

**Comment by kinow** [comment]
I recently fixed the pages for biouno.org. I believe I can find some time this week to go through the commits to that repo, build the site locally with jekyll and send a pull request to fix it.

**Comment by iamciera** [comment]
Cool! Yeah, please do if you find some time. Thanks @kinow.

**Comment by kinow** [comment]
Tried building it locally, here's the error I got:

```
kinow@ranma:~/Development/java/workspace/reproducibility-guide$ jekyll serve
Configuration file: /home/kinow/Development/java/workspace/reproducibility-guide/_config.yml
       Deprecation: The 'pygments' configuration option has been renamed to 'highlighter'. Please update your config file accordingly. The allowed values are 'rouge', 'pygments' or null.
            Source: /home/kinow/Development/java/workspace/reproducibility-guide
       Destination: /home/kinow/Development/java/workspace/reproducibility-guide/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Dependency Error: Yikes! It looks like you don't have redcarpet or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- redcarpet' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2014-03-02-Useful-Workflows.md':
                    redcarpet
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    redcarpet
```

Comparing commits in the biouno repository and picking the ones I think will fix it. Pull request coming in a few minutes.

**Comment by kinow** [comment]
Fixed the error by `sudo gem install redcarpet`

**Comment by kinow** [comment]
Site built successfully, and running. Now creating pull request with changes, which will include replacing redcarpet by kramdown.

**Comment by kinow** [comment]
Here's the reason for using kramdown, from the post https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0:

> Starting May 1st, 2016, GitHub Pages will only support kramdown, Jekyll's default Markdown engine. If you are currently using Rdiscount or Redcarpet we've enabled kramdown's GitHub-flavored Markdown support by default, meaning kramdown should have all the features of the two deprecated Markdown engines, so the transition should be as simple as updating the Markdown setting to kramdown in your site's configuration (or removing it entirely) over the course of the next three months.

However there are pages that will need to be updated. For example, the check list, where <br /> are used to break line. That does not work with kramdown. See https://github.com/gettalong/kramdown/issues/137 for more, specifically the last comment there from gettalong.

> Line breaks in Markdown/kramdown are not treated as hard line breaks but as line continuations. If you need to separate two paragraphs, use a blank line.
> 
> If you want to insert a <br /> tag, use two spaces at the end of a line. See http://kramdown.gettalong.org/syntax.html for more information.

**Comment by kinow** [comment]
Looks like that page is the only one with <br> tags. So fixing it with:

```
grep -r -i --include \*.md -E "(.*)(</br>)\s*$" * | awk -F: '{ print $1 }' | uniq | xargs -I {} sed -i -e 's/\(.*\)\(<\/br>\)\s*$/\1  /' {}
```

**Comment by kinow** [comment]
@jhollist reported an issue against biouno website, and looks like we'd have the same problem here. So re-using the same solution to fix missing space between the last # in the Markdown header and the first char.

```
grep -r -i --include \*.md --include \*.html -E "^#+[a-zA-Z0-9].*" * | awk -F: '{ print $1 }' | uniq | xargs -I {} sed -i -e 's/^\(#\)\([a-zA-Z0-9]\)/\1 \2/' -e 's/^\(##\)\([a-zA-Z0-9]\)/\1 \2/' -e 's/^\(###\)\([a-zA-Z0-9]\)/\1 \2/' -e 's/^\(####\)\([a-zA-Z0-9]\)/\1 \2/' {}
```

**Comment by kinow** [comment]
Done @iamciera. See pull request #91. @jhollist wonder if you could review it, maybe?

Thanks!

**Comment by jhollist** [comment]
@kinow and @iamciera happy to review it.  Will look at it today.

And thanks for sharing the one liner to do the replacements!  That would have taken me years to figure out!

**Comment by jhollist** [comment]
@iamciera this should be fixed now.  I just accepted PR #91.

If you can confirm that there are no more build errors, then we can close this issue.
