### ISSUE TITLE
Broken link in Writing code section

### ISSUE THREAD

**Issue by alexknorre** [ropensci-archive/reproducibility-guide#94]
Links to Gentzkow and Shapiro' writing code manuals are broken. The proper one is http://web.stanford.edu/~gentzkow/research/CodeAndData.pdf . As Gentzkow wrote,  '[it] includes material previously circulated as "Notes for RAs on Writing Code"'

**Comment by iamciera** [comment]
Thanks for finding it @alexeyknorre , you can go ahead and create a pull request to fix if you want.  If not, I will get to it in a bit.

**Comment by alexknorre** [comment]
Thanks @iamciera , created a pull request, wasn't sure about branch so it's gh-pages
